---
services:
  hato-bot-go:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: prod
      cache_from:
        - ghcr.io/${REPOSITORY:-massongit/hato-bot-go}/hato-bot-go:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-massongit/hato-bot-go}/hato-bot-go
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: ghcr.io/${REPOSITORY:-massongit/hato-bot-go}/hato-bot-go:${TAG_NAME}