---
services:
  hato-bot-go:
    build:
      target: dev
      cache_from:
        - type=registry,ref=ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:buildcache
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go-dev:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go-dev
      cache_to:
        - type=registry,ref=ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:buildcache,mode=max
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go-dev:${TAG_NAME}
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/tmp
