---
services:
  hato-bot-go:
    environment:
      - MISSKEY_DOMAIN=${MISSKEY_DOMAIN}
      - MISSKEY_API_TOKEN=${MISSKEY_API_TOKEN}
      - YAHOO_API_TOKEN=${YAHOO_API_TOKEN}
    restart: unless-stopped
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
