---
services:
  hato-bot-go:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      - MISSKEY_DOMAIN=${MISSKEY_DOMAIN}
      - MISSKEY_API_TOKEN=${MISSKEY_API_TOKEN}
      - MIXI2_CLIENT_ID=${MIXI2_CLIENT_ID}
      - MIXI2_CLIENT_SECRET=${MIXI2_CLIENT_SECRET}
      - MIXI2_TOKEN_URL=${MIXI2_TOKEN_URL}
      - MIXI2_API_ADDRESS=${MIXI2_API_ADDRESS}
      - MIXI2_STREAM_ADDRESS=${MIXI2_STREAM_ADDRESS}
      - YAHOO_API_TOKEN=${YAHOO_API_TOKEN}
    restart: unless-stopped
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
