---
services:
  hato-bot-go:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: prod
      cache_from:
        - ghcr.io/${REPOSITORY:-hato-bot/hato-bot-go}/hato-bot-go:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-hato-bot/hato-bot-go}/hato-bot-go
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: ghcr.io/${REPOSITORY:-hato-bot/hato-bot-go}/hato-bot-go:${TAG_NAME}
    environment:
      - MISSKEY_DOMAIN=${MISSKEY_DOMAIN}
      - MISSKEY_API_TOKEN=${MISSKEY_API_TOKEN}
      - YAHOO_API_TOKEN=${YAHOO_API_TOKEN}
    restart: unless-stopped
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
