---
services:
  hato-bot-go:
    build:
      target: prod_misskey
      cache_from:
        - type=registry,ref=ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:buildcache
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:misskey-${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go
      cache_to:
        - type=registry,ref=ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:buildcache,mode=max
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:misskey-${TAG_NAME}
