---
services:
  hato-bot-go:
    build:
      target: prod_misskey
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:misskey-${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot-go}/hato-bot-go:misskey-${TAG_NAME}
