---
services:
  hato-bot-go:
    build:
      target: prod_mixi2
      cache_from:
        - ghcr.io/${REPOSITORY:-hato-bot/hato-bot-go}/hato-bot-go:mixi2-${TAG_NAME}
        - ghcr.io/${REPOSITORY:-hato-bot/hato-bot-go}/hato-bot-go
    image: ghcr.io/${REPOSITORY:-hato-bot/hato-bot-go}/hato-bot-go:mixi2-${TAG_NAME}
