// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mixigroup/mixi2-application-sdk-go/auth (interfaces: Authenticator)
//
// Generated by this command:
//
//	mockgen -destination mock_authenticator.go -package mixi2 -typed github.com/mixigroup/mixi2-application-sdk-go/auth Authenticator
//

// Package mixi2 is a generated GoMock package.
package mixi2

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// AuthorizedContext mocks base method.
func (m *MockAuthenticator) AuthorizedContext(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizedContext", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizedContext indicates an expected call of AuthorizedContext.
func (mr *MockAuthenticatorMockRecorder) AuthorizedContext(ctx any) *MockAuthenticatorAuthorizedContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizedContext", reflect.TypeOf((*MockAuthenticator)(nil).AuthorizedContext), ctx)
	return &MockAuthenticatorAuthorizedContextCall{Call: call}
}

// MockAuthenticatorAuthorizedContextCall wrap *gomock.Call
type MockAuthenticatorAuthorizedContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorAuthorizedContextCall) Return(arg0 context.Context, arg1 error) *MockAuthenticatorAuthorizedContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorAuthorizedContextCall) Do(f func(context.Context) (context.Context, error)) *MockAuthenticatorAuthorizedContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorAuthorizedContextCall) DoAndReturn(f func(context.Context) (context.Context, error)) *MockAuthenticatorAuthorizedContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAccessToken mocks base method.
func (m *MockAuthenticator) GetAccessToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockAuthenticatorMockRecorder) GetAccessToken(ctx any) *MockAuthenticatorGetAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockAuthenticator)(nil).GetAccessToken), ctx)
	return &MockAuthenticatorGetAccessTokenCall{Call: call}
}

// MockAuthenticatorGetAccessTokenCall wrap *gomock.Call
type MockAuthenticatorGetAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorGetAccessTokenCall) Return(arg0 string, arg1 error) *MockAuthenticatorGetAccessTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorGetAccessTokenCall) Do(f func(context.Context) (string, error)) *MockAuthenticatorGetAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorGetAccessTokenCall) DoAndReturn(f func(context.Context) (string, error)) *MockAuthenticatorGetAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
