// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mixigroup/mixi2-application-sdk-go/gen/go/social/mixi/application/service/application_api/v1 (interfaces: ApplicationServiceClient)
//
// Generated by this command:
//
//	mockgen -destination mock_api_client.go -package mixi2 github.com/mixigroup/mixi2-application-sdk-go/gen/go/social/mixi/application/service/application_api/v1 ApplicationServiceClient
//

// Package mixi2 is a generated GoMock package.
package mixi2

import (
	context "context"
	reflect "reflect"

	application_apiv1 "github.com/mixigroup/mixi2-application-sdk-go/gen/go/social/mixi/application/service/application_api/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockApplicationServiceClient is a mock of ApplicationServiceClient interface.
type MockApplicationServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationServiceClientMockRecorder
	isgomock struct{}
}

// MockApplicationServiceClientMockRecorder is the mock recorder for MockApplicationServiceClient.
type MockApplicationServiceClientMockRecorder struct {
	mock *MockApplicationServiceClient
}

// NewMockApplicationServiceClient creates a new mock instance.
func NewMockApplicationServiceClient(ctrl *gomock.Controller) *MockApplicationServiceClient {
	mock := &MockApplicationServiceClient{ctrl: ctrl}
	mock.recorder = &MockApplicationServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationServiceClient) EXPECT() *MockApplicationServiceClientMockRecorder {
	return m.recorder
}

// AddStampToPost mocks base method.
func (m *MockApplicationServiceClient) AddStampToPost(ctx context.Context, in *application_apiv1.AddStampToPostRequest, opts ...grpc.CallOption) (*application_apiv1.AddStampToPostResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddStampToPost", varargs...)
	ret0, _ := ret[0].(*application_apiv1.AddStampToPostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStampToPost indicates an expected call of AddStampToPost.
func (mr *MockApplicationServiceClientMockRecorder) AddStampToPost(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStampToPost", reflect.TypeOf((*MockApplicationServiceClient)(nil).AddStampToPost), varargs...)
}

// CreatePost mocks base method.
func (m *MockApplicationServiceClient) CreatePost(ctx context.Context, in *application_apiv1.CreatePostRequest, opts ...grpc.CallOption) (*application_apiv1.CreatePostResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePost", varargs...)
	ret0, _ := ret[0].(*application_apiv1.CreatePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockApplicationServiceClientMockRecorder) CreatePost(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockApplicationServiceClient)(nil).CreatePost), varargs...)
}

// DeletePost mocks base method.
func (m *MockApplicationServiceClient) DeletePost(ctx context.Context, in *application_apiv1.DeletePostRequest, opts ...grpc.CallOption) (*application_apiv1.DeletePostResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePost", varargs...)
	ret0, _ := ret[0].(*application_apiv1.DeletePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockApplicationServiceClientMockRecorder) DeletePost(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockApplicationServiceClient)(nil).DeletePost), varargs...)
}

// GetPostMediaStatus mocks base method.
func (m *MockApplicationServiceClient) GetPostMediaStatus(ctx context.Context, in *application_apiv1.GetPostMediaStatusRequest, opts ...grpc.CallOption) (*application_apiv1.GetPostMediaStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostMediaStatus", varargs...)
	ret0, _ := ret[0].(*application_apiv1.GetPostMediaStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostMediaStatus indicates an expected call of GetPostMediaStatus.
func (mr *MockApplicationServiceClientMockRecorder) GetPostMediaStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostMediaStatus", reflect.TypeOf((*MockApplicationServiceClient)(nil).GetPostMediaStatus), varargs...)
}

// GetPosts mocks base method.
func (m *MockApplicationServiceClient) GetPosts(ctx context.Context, in *application_apiv1.GetPostsRequest, opts ...grpc.CallOption) (*application_apiv1.GetPostsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPosts", varargs...)
	ret0, _ := ret[0].(*application_apiv1.GetPostsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockApplicationServiceClientMockRecorder) GetPosts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockApplicationServiceClient)(nil).GetPosts), varargs...)
}

// GetStamps mocks base method.
func (m *MockApplicationServiceClient) GetStamps(ctx context.Context, in *application_apiv1.GetStampsRequest, opts ...grpc.CallOption) (*application_apiv1.GetStampsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStamps", varargs...)
	ret0, _ := ret[0].(*application_apiv1.GetStampsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStamps indicates an expected call of GetStamps.
func (mr *MockApplicationServiceClientMockRecorder) GetStamps(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStamps", reflect.TypeOf((*MockApplicationServiceClient)(nil).GetStamps), varargs...)
}

// GetUsers mocks base method.
func (m *MockApplicationServiceClient) GetUsers(ctx context.Context, in *application_apiv1.GetUsersRequest, opts ...grpc.CallOption) (*application_apiv1.GetUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsers", varargs...)
	ret0, _ := ret[0].(*application_apiv1.GetUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockApplicationServiceClientMockRecorder) GetUsers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockApplicationServiceClient)(nil).GetUsers), varargs...)
}

// InitiatePostMediaUpload mocks base method.
func (m *MockApplicationServiceClient) InitiatePostMediaUpload(ctx context.Context, in *application_apiv1.InitiatePostMediaUploadRequest, opts ...grpc.CallOption) (*application_apiv1.InitiatePostMediaUploadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InitiatePostMediaUpload", varargs...)
	ret0, _ := ret[0].(*application_apiv1.InitiatePostMediaUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiatePostMediaUpload indicates an expected call of InitiatePostMediaUpload.
func (mr *MockApplicationServiceClientMockRecorder) InitiatePostMediaUpload(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiatePostMediaUpload", reflect.TypeOf((*MockApplicationServiceClient)(nil).InitiatePostMediaUpload), varargs...)
}

// SendChatMessage mocks base method.
func (m *MockApplicationServiceClient) SendChatMessage(ctx context.Context, in *application_apiv1.SendChatMessageRequest, opts ...grpc.CallOption) (*application_apiv1.SendChatMessageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendChatMessage", varargs...)
	ret0, _ := ret[0].(*application_apiv1.SendChatMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendChatMessage indicates an expected call of SendChatMessage.
func (mr *MockApplicationServiceClientMockRecorder) SendChatMessage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChatMessage", reflect.TypeOf((*MockApplicationServiceClient)(nil).SendChatMessage), varargs...)
}
