---
name: pr-format
# pull_requestで何かあった時に起動する
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  # PRが来たらformatをかけてみて、差分があればPRを作って、エラーで落ちるjob
  # jscpd:ignore-start
  pr-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          go-version-file: go.mod
      # jscpd:ignore-end
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        uses: flatt-security/setup-takumi-guard-golang@2e3c7c40b538cd68b2ac483def12982ebc8bc02e # v1
      # formatする
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: bash "${GITHUB_WORKSPACE}/scripts/pr_format/pr_format/format.sh"
      - uses: dev-hato/actions-diff-pr-management@571be0d9572aaf77cdd315c12d6e73a1112910d7 # v2.2.6
        if: success() || failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-format
          pr-title-prefix: formatが間違ってたので直してあげたよ！
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
