---
name: pr-main-to-develop-hato-bot-go
on:
  push:
    branches:
      - main
jobs:
  # mainにコミットがpushされたら、それをdevelopに反映するPRを作成するjob
  # mainとdevelopの間でコミットログに差異が出ないようにする
  pr-main-to-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - name: Get PullRequests
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: get_pull_requests
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {tsImport} = require('tsx/esm/api')
            const {script} = await tsImport(
              './scripts/get_pull_requests_hato_bot.ts',
              process.env.GITHUB_WORKSPACE + '/'
            )
            return await script(github, context)
      - name: Create PullRequest
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: ${{ steps.get_pull_requests.outputs.result == 0 }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {tsImport} = require('tsx/esm/api')
            const {script} = await tsImport(
              './scripts/pr_merge_develop_hato_bot/pr_main_to_develop/create_pull_request.ts',
              process.env.GITHUB_WORKSPACE + '/'
            )
            await script(github, context)
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
